### ISSUE TITLE
Racecondition when clicking around in menus fast

### ISSUE THREAD

**Issue by Prior99** [svenstaro/innojam9#2]
There is a rare racecondition occuring seemingly randomly when clicking around in menus fast.
It seems the be related to the render loop.

**Comment by Prior99** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff678fd68 in main_arena () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff678fd68 in main_arena () from /usr/lib/libc.so.6
#1  0x00007ffff7296a8c in ?? () from /usr/lib/libSDL2-2.0.so.0
#2  0x00000000004b617c in MenuState::draw (this=0x230b3f0, dt=0.017000000000000001)
    at /home/prior/Projects/innojam9/src/menu_state.cpp:178
#3  0x00000000004b5a4b in MenuState::update (this=0x230b3f0, dt=0.017000000000000001)
    at /home/prior/Projects/innojam9/src/menu_state.cpp:106
#4  0x00000000004f3ec7 in Game::mainloop (this=0x7fffffffe440)
    at /home/prior/Projects/innojam9/src/game.cpp:129
#5  0x00000000004bd961 in mainloop (args=0x7fffffffe440) at /home/prior/Projects/innojam9/src/main.cpp:9
#6  0x00000000004bd9c0 in main () at /home/prior/Projects/innojam9/src/main.cpp:22
```
